#!/usr/bin/env bash

alias sudo="sudo "
alias please="sudo "
alias update="yay -Syyu"
alias vim="nvim"
alias lsa="ls -lah"

alias ccpp="g++ -ggdb -pedantic-errors -Wall -Weffc++ -Wextra -Wconversion -Wsign-conversion -Werror -std=c++20"
