-- Disabling netrw for nvim-tree
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

require("kazuma.impatient")
require("kazuma.options")
require("kazuma.keymaps")
require("kazuma.plugins")
require("kazuma.autocmds")
require("kazuma.catppuccin")
require("kazuma.cmp")
require("kazuma.lsp")
require("kazuma.telescope")
require("kazuma.treesitter")
require("kazuma.autopairs")
require("kazuma.comment")
require("kazuma.gitsigns")
require("kazuma.nvimtree")
require("kazuma.barbar")
require("kazuma.lualine")
require("kazuma.toggleterm")
require("kazuma.project")
require("kazuma.illuminate")
require("kazuma.indentline")
require("kazuma.alpha")
require("kazuma.dap")
require("kazuma.coderunner")
-- require("kazuma.whichkey")
