import:
    - ~/.config/alacritty/catppuccin-mocha.yml

env:
    WINIT_X11_SCALE_FACTOR: "1.0"

# TERM: xterm-256color

window:
    padding:
        x: 2
        y: 2
    dynamic_padding: true
    opacity: 0.9

font:
    normal:
        family: FiraCode Nerd Font
        style: Regular

    bold:
        family: FiraCode Nerd Font
        style: Bold

    italic:
        family: FiraCode Nerd Font
        style: Italic

    size: 12
