import:
    - ~/.config/alacritty/catppuccin-mocha.yml

env:
    WINIT_X11_SCALE_FACTOR: "1.0"

# TERM: xterm-256color

window:
    padding:
        x: 5
        y: 5
    opacity: 0.8

font:
    normal:
        family: Hack Nerd Font
        style: Regular

    bold:
        family: Hack Nerd Font

    italic:
        family: Hack Nerd Font

    size: 12
