import = ["/home/kazuma/.config/alacritty/catppuccin-mocha.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 2
y = 2
