import = ["/home/kazuma/.config/alacritty/catppuccin-mocha.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 12

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 2
y = 2
